services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    env_file: .env
    networks:
      - inception
    ports:
      - "443:443"
    expose:
      - 433
    restart: on-failure
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - /home/tiagoliv/data/wordpress:/var/www/html/
    env_file: .env
    networks:
      - inception
    expose:
      - 9000
    restart: on-failure
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - /home/tiagoliv/data/mariadb:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    expose:
      - 3306
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge
