version: '3.8'

services:
  mariadb_data:
    name: mariadb_data
    volumes:
      - /home/tiagoliv/data/mysql:var/lib/mysql
  wordpress_data:
    name: wordpress_data
    volumes:
      - /home/tagoliv/data/wordpress:var/lib/wordpress